---
AllCops:
  NewCops: enable

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
